### ISSUE TITLE
Assertion failure with LocalScan

### ISSUE THREAD

**Issue by tomyun** [yuyichao/FunctionWrappers.jl#17]
I have a strange error with the master branch of FunctionWrappers seeming related to the recently merged #15. I couldn't come up with a MWE yet, but the error message is like this:

```
Assertion failed: (SRet), function LocalScan, file /Users/julia/buildbot/worker/package_macos64/build/src/llvm-late-gc-lowering.cpp, line 1372.

signal (6): Abort trap: 6
in expression starting at /Users/tomyun/...
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 204885385 (Pool: 204829043; Big: 56342); GC: 172
```

When I modified FunctionWrappers to use `isbitstype()` instead of `Base.allocatedinline()` as it used to do, then the code would start working fine again. Do you have any ideas on what could cause this? I tested it on Julia 1.5.1.

**Comment by yuyichao** [comment]
Almost definitely base bug.
