### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dantaras** [yuyichao/FunctionWrappers.jl#18]
Any chance you can tag & release the latest version of this? Julia 1.6 is quite close now and FunctionWrappers 1.1.1 isn't compatible with it.

**Comment by sethaxen** [comment]
In what way is the latest release incompatible with Julia 1.6? Nothing in the version bounds blocks it. If you are seeing an error, please describe it.

**Comment by ChrisRackauckas** [comment]
Something internally changed https://github.com/yuyichao/FunctionWrappers.jl/compare/v1.1.1...master#commitcomment-41934634

**Comment by dantaras** [comment]
Sorry, I thought you were aware because of https://github.com/yuyichao/FunctionWrappers.jl/issues/16.
For the code below:
```
using FunctionWrappers
FunctionWrappers.FunctionWrapper{Nothing, Tuple{Int}}(x -> nothing)(1)
```

I'm getting:
```
ERROR: LoadError: Module IR does not contain specified entry function
Stacktrace:
 [1] assume
   @ ~/.julia/packages/FunctionWrappers/OAZAk/src/FunctionWrappers.jl:9 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/FunctionWrappers/OAZAk/src/FunctionWrappers.jl:107 [inlined]
 [3] do_ccall
   @ ~/.julia/packages/FunctionWrappers/OAZAk/src/FunctionWrappers.jl:97 [inlined]
 [4] (::FunctionWrappers.FunctionWrapper{Nothing, Tuple{Int64}})(args::Int64)
   @ FunctionWrappers ~/.julia/packages/FunctionWrappers/OAZAk/src/FunctionWrappers.jl:116
 [5] top-level scope
   @ ~/test/function_wrappers.jl:3
```

This only happens with FunctionWrappers 1.1.1 and julia-1.6.0-rc1. FunctionWrappers master doesn't have this issue and neither has FunctionWappers 1.1.1 with julia-1.5.2
