### ISSUE TITLE
Union return type results in error on Julia 1.8

### ISSUE THREAD

**Issue by danielmatz** [yuyichao/FunctionWrappers.jl#28]
The following has been working on the last several versions of Julia, but has now started producing an error on Julia 1.8:

```julia
julia> FunctionWrappers.FunctionWrapper{Union{Nothing, Float64}, Tuple{}}(() -> nothing)
ERROR: cfunction method definition: return type doesn't correspond to a C type
Stacktrace:
 [1] FunctionWrappers.FunctionWrapper{Union{Nothing, Float64}, Tuple{}}(obj::var"#33#34")
   @ FunctionWrappers ~/.julia/packages/FunctionWrappers/8xdVB/src/FunctionWrappers.jl:100
 [2] top-level scope
   @ REPL[29]:1
```

I see that the FunctionWrappers code tries to wrap return types in `Ref` in certain situations. It seems that this would happen on Julia 1.7 but not on Julia 1.8.

For Julia 1.7, the return type gets wrapped if `Base.allocatedinline` returns `true`:
```julia
julia> Base.allocatedinline(Union{Nothing, Float64})
true
```

And for Julia 1.8, the return type gets wrapped if `isbitstype` returns `true`:
```julia
julia> isbitstype(Union{Nothing, Float64})
false
```

And, if I manually wrap the return type, I can get it to work on Julia 1.8:

```julia
julia> f = FunctionWrappers.FunctionWrapper{Base.RefValue{Union{Nothing, Float64}}, Tuple{}}(() -> Ref{Union{Nothing, Float64}}(nothing))
FunctionWrappers.FunctionWrapper{Base.RefValue{Union{Nothing, Float64}}, Tuple{}}(Ptr{Nothing} @0x00000001184314a0, Ptr{Nothing} @0x0000000156e14820, Base.RefValue{var"#35#36"}(var"#35#36"()), var"#35#36")

julia> f()
Base.RefValue{Union{Nothing, Float64}}(nothing)
```

Is this a bug in FunctionWrappers, or should I be manually wrapping return types in `Ref`?

**Comment by yuyichao** [comment]
> I see that the FunctionWrappers code tries to wrap return types in `Ref` in certain situations. It seems that this would happen on Julia 1.7 but not on Julia 1.8.

You actually got that logic reversed. Union does not need to be wrapped on 1.7 but does on 1.8. The logic you saw is exactly what does that on master.

Assuming I did things correctly a new release with that fix should be available soon.

**Comment by danielmatz** [comment]
> You actually got that logic reversed.

Ha! Yes, sorry about that.

> Assuming I did things correctly a new release with that fix should be available soon.

Thank you!

**Comment by danielmatz** [comment]
I was able to grab the new release. Thank you again.

However, I don't see a new tag here, FYI.

**Comment by yuyichao** [comment]
Yeah I don't think the tagbot is working and I'm too lazy to figure it out. I'll probably just tag it manually like what I've always been doing previously anyway...
