### ISSUE TITLE
Script works in REPL but fails with debugger

### ISSUE THREAD

**Issue by JockLawrie** [yuyichao/FunctionWrappers.jl#29]
Hi there, the script below works in the REPL but fails when debugging in VSCode.
What's happening here?
Is there a workaround so that I can use the debugger with programs that use FunctionWrappers?

```julia
using FunctionWrappers

f    = (obs) -> (obs[1] = obs[3] * obs[4]; obs)
Tout = Vector{Int}
Tin  = Tuple{Vector{Int}}
fw   = FunctionWrappers.FunctionWrapper{Tout, Tin}(f)

obs = [0,2,3,4]
fw(obs)
```

**Comment by yuyichao** [comment]
what do you mean by "fails when debugging in VSCode".

**Comment by JockLawrie** [comment]
![image](https://user-images.githubusercontent.com/11449078/201250322-5149396b-d726-4e28-90e0-3d2706891f51.png)

**Comment by yuyichao** [comment]
Well. Clearly the debugger is unable to handle llvmcall and that’s not really an issue of this package…

**Comment by JockLawrie** [comment]
ok thanks
