### ISSUE TITLE
Transfer to JuliaLang repo?

### ISSUE THREAD

**Issue by ViralBShah** [yuyichao/FunctionWrappers.jl#32]
@yuyichao Would you be open to moving this to the JuliaLang repo so that it can receive continued maintenance? Naturally, you already have access there, and we'll make sure you have admin access going forward.

cc @vtjnash

**Comment by yuyichao** [comment]
Sure that's fine.

**Comment by yuyichao** [comment]
Done.

**Comment by ViralBShah** [comment]
Thank you!
