### ISSUE TITLE
First Time User Guide / Examples

### ISSUE THREAD

**Issue by GravityAssisted** [yuyichao/FunctionWrappers.jl#5]
I am relatively new to Julia and I was redirected to this from [here](https://discourse.julialang.org/t/function-in-type-definition/3790/22) , but i cant seem to find any documentation on how to use this package. Is there any example source I can look at the get an idea on how this package might be used ?

thanks

**Comment by yuyichao** [comment]
All supported usages are pretty much in the test.

**Comment by GravityAssisted** [comment]
Yeah, I figured it out, thanks. I do have a question though, lets take the following example:
```
i, j, k are user inputs
const F64F64Func = FunctionWrapper{Float64,Tuple{Float64}}
const dict = Vector{F64F64Func}(k)
f1(x::Float64) = 1.0 + x
dict[i] = f1
f2(x::Float64) = 1.0 - x
dict[j] = f2
```
where ```i``` and ```j``` can be 1 to ```k``` depending on the user input values. So my questions are 

1. Does the code needs recompilation every time the user inputs i and j ?
2. Does the code need recompilation if length of dict vector grows based on user inputs ? (k changes) (most likely case for me)

I am trying to understand how much abstraction I can get before I result in a dynamic dispatch or trigger recompilation.

thanks!

**Comment by yuyichao** [comment]
For leaf arg type, the compilation is never done at call time and there is never dynamic dispatch.

This package does not affect recompilation. If you can call the function you are passing without recompilation then there won't be recompilation with this pacakge either.

The code you give does not provide enough context to answer your question.

**Comment by GravityAssisted** [comment]
Thanks!
